#!/bin/bash

#
# Lists commits (volume snapshots) for the given repo
#
#   log <repo>
#

function usage() {
  echo "Usage: titan log <repo>" 1>&2
  exit 2
}

while getopts ":" o; do
  case "${o}" in
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))
repo_name=$1

[[ -z "$repo_name" ]] && usage

# Get any volume snapshots associated with the release
snapshots=$(kubectl get --selector=release=$repo_name volumesnapshot --no-headers -o custom-columns=":metadata.name")
for snap in $snapshots; do
  commit=${snap#$repo_name-}
  creation=$(kubectl get volumesnapshot $snap --template "{{.metadata.creationTimestamp}}")
  echo "Commit $commit"
  echo "Date: $creation"
  echo ""
done
