#!/bin/bash

#
# Lists helm charts (a.k.a. repositories)
#
#   ls
#

function usage() {
  echo "Usage: titan ls" 1>&2
  exit 2
}

while getopts ":" o; do
  case "${o}" in
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))
[[ $# == 0 ]] || usage

exec helm ls
