#!/bin/bash

#
# Lists helm charts (a.k.a. repositories)
#
#   rm <repo>
#

function usage() {
  echo "Usage: titan rm" 1>&2
  exit 2
}

while getopts ":" o; do
  case "${o}" in
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))
repo_name=$1

[[ -z "$repo_name" ]] && usage

# Remove any port forwarding
services=$(kubectl get --selector=release=hello-world service --no-headers -o custom-columns=":metadata.name")
for service in $services; do
    ps -ef | grep "kubectl port-forward" | grep "svc/$service"  | awk '{print $2}' | xargs kill
done

# Remove the helm release
helm delete --purge $repo_name || exit 1

# Remove any remaining volumes
pvcs=$(kubectl get --selector=release=hello-world pvc --no-headers -o custom-columns=":metadata.name")
for pvc in $pvcs; do
    kubectl delete pvc $pvc
done
