#!/bin/bash

#
# Lists helm charts (a.k.a. repositories)
#
#   rm <repo>
#

function usage() {
  echo "Usage: titan rm" 1>&2
  exit 2
}

while getopts ":" o; do
  case "${o}" in
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))
repo_name=$1

[[ -z "$repo_name" ]] && usage

echo "Stopping port forwarding"
services=$(kubectl get --selector=release=$repo_name service --no-headers -o custom-columns=":metadata.name")
for service in $services; do
    ps -ef | grep "kubectl port-forward" | grep "svc/$service"  | awk '{print $2}' | xargs kill
done

echo "Deleting release"
helm delete --purge $repo_name || exit 1

echo "Deleting volumes"
pvcs=$(kubectl get --selector=release=$repo_name pvc --no-headers -o custom-columns=":metadata.name")
for pvc in $pvcs; do
    kubectl delete pvc $pvc
done

echo "Deleting snapshots"
snapshots=$(kubectl get --selector=release=$repo_name volumesnapshot --no-headers -o custom-columns=":metadata.name")
for snap in $snapshots; do
    kubectl delete volumesnapshot $snap
done
