#!/bin/bash

#
# Runs a helm chart.
#
#   run <-n name> <char>
#

function usage() {
  echo "Usage: titan run [-p name=value] <-n name> <source>" 1>&2
  exit 2
}

helm_args=
while getopts ":n:p:" o; do
  case "${o}" in
    n)
      repo_name=$OPTARG
      ;;
    p)
      helm_args="$helm_args --set $OPTARG"
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))
image_name=$1

[[ -z "$image_name" ]] && usage
[[ -z "$repo_name" ]] && usage

exec helm install --name $repo_name --wait $helm_args $image_name
