#!/bin/bash

#
# Runs a helm chart.
#
#   run <-n name> <char>
#

function usage() {
  echo "Usage: titan run [-p name=value] <-n name> <source>" 1>&2
  exit 2
}

helm_args=
while getopts ":n:p:" o; do
  case "${o}" in
    n)
      repo_name=$OPTARG
      ;;
    p)
      helm_args="$helm_args --set $OPTARG"
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))
image_name=$1

[[ -z "$image_name" ]] && usage
[[ -z "$repo_name" ]] && usage

helm install --name $repo_name --wait $helm_args $image_name || exit 1

services=$(kubectl get --selector=release=$repo_name service --no-headers -o custom-columns=":metadata.name")
for service in $services; do
    if [[ $service != *"headless" ]]; then
        ports=$(kubectl get service $service --template '{{range .spec.ports}}{{.port}}{{"\n"}}{{end}}')
        for port in $ports; do
            echo kubectl port-forward --namespace default svc/$service $port:$port
            kubectl port-forward --namespace default svc/$service $port:$port >/dev/null 2>&1 &
        done
    fi
done
